name: Check pull request

on:
  pull_request:

jobs:
  # ci:
    # uses: ./.github/workflows/ci.yml

  release:
      runs-on: macos-latest
      # needs: ci
      env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Get project version
            id: get_version
            run: |
              version=$(./gradlew -q properties | grep '^version:' | awk '{print $2}')
              echo "version=$version" >> $GITHUB_OUTPUT
              echo "Project version: $version"

          - name: Set PR SNAPSHOT version
            id: set_version
            run: |
              base_version="${{ steps.get_version.outputs.version }}"
              pr_number="${{ github.event.pull_request.number }}"
              pr_version="${base_version/SNAPSHOT/PR${pr_number}-SNAPSHOT}"
              echo "pr_version=$pr_version" >> $GITHUB_OUTPUT
              if [[ "$pr_version" == *PR* && "$pr_version" == *SNAPSHOT* ]]; then
                echo "Publishing version: $pr_version"
              else
                echo "Wrong PR version format: $pr_version"
                exit 1
              fi

          - name: Publish to Sonatype Snapshot
            run: ./gradlew publishAllPublicationsToSonatypeSnapshotRepository -PGPG_SIGNING_REQUIRED -Pversion=${{ steps.set_version.outputs.pr_version }} --no-configuration-cache
