name: Release to maven central snapshots

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  release:
    runs-on: macos-latest
    env:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract pre-release identifier
        id: prerelease
        run: |
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                echo "prerelease=${{ github.event.pull_request.number }}-SNAPSHOT" >> $GITHUB_OUTPUT
            else
                echo "prerelease=SNAPSHOT" >> $GITHUB_OUTPUT
            fi

      - name: Publish to Sonatype Snapshot
        run: ./gradlew publishAllPublicationsToSonatypeSnapshotRepository -PPRE_RELEASE_IDENTIFIER=${{ steps.prerelease.outputs.prerelease }} -PGPG_SIGNING_REQUIRED --no-configuration-cache
